/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OndeComerRouteImport } from './routes/onde-comer'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresaIdRouteImport } from './routes/empresa.$id'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminAprovacoesRouteImport } from './routes/_authenticated/admin.aprovacoes'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeComerRoute = OndeComerRouteImport.update({
  id: '/onde-comer',
  path: '/onde-comer',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaIdRoute = EmpresaIdRouteImport.update({
  id: '/empresa/$id',
  path: '/empresa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAprovacoesRoute =
  AuthenticatedAdminAprovacoesRouteImport.update({
    id: '/aprovacoes',
    path: '/aprovacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guia': typeof GuiaRoute
  '/imoveis': typeof ImoveisRoute
  '/noticias': typeof NoticiasRoute
  '/onde-comer': typeof OndeComerRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vagas': typeof VagasRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guia': typeof GuiaRoute
  '/imoveis': typeof ImoveisRoute
  '/noticias': typeof NoticiasRoute
  '/onde-comer': typeof OndeComerRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vagas': typeof VagasRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/guia': typeof GuiaRoute
  '/imoveis': typeof ImoveisRoute
  '/noticias': typeof NoticiasRoute
  '/onde-comer': typeof OndeComerRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vagas': typeof VagasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/_authenticated/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/guia'
    | '/imoveis'
    | '/noticias'
    | '/onde-comer'
    | '/perfil'
    | '/sitemap.xml'
    | '/vagas'
    | '/admin'
    | '/minha-conta'
    | '/empresa/$id'
    | '/admin/aprovacoes'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/guia'
    | '/imoveis'
    | '/noticias'
    | '/onde-comer'
    | '/perfil'
    | '/sitemap.xml'
    | '/vagas'
    | '/minha-conta'
    | '/empresa/$id'
    | '/admin/aprovacoes'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/guia'
    | '/imoveis'
    | '/noticias'
    | '/onde-comer'
    | '/perfil'
    | '/sitemap.xml'
    | '/vagas'
    | '/_authenticated/admin'
    | '/_authenticated/minha-conta'
    | '/empresa/$id'
    | '/_authenticated/admin/aprovacoes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GuiaRoute: typeof GuiaRoute
  ImoveisRoute: typeof ImoveisRoute
  NoticiasRoute: typeof NoticiasRoute
  OndeComerRoute: typeof OndeComerRoute
  PerfilRoute: typeof PerfilRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VagasRoute: typeof VagasRoute
  EmpresaIdRoute: typeof EmpresaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-comer': {
      id: '/onde-comer'
      path: '/onde-comer'
      fullPath: '/onde-comer'
      preLoaderRoute: typeof OndeComerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/$id': {
      id: '/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/empresa/$id'
      preLoaderRoute: typeof EmpresaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aprovacoes': {
      id: '/_authenticated/admin/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/admin/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAdminAprovacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAprovacoesRoute: typeof AuthenticatedAdminAprovacoesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAprovacoesRoute: AuthenticatedAdminAprovacoesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GuiaRoute: GuiaRoute,
  ImoveisRoute: ImoveisRoute,
  NoticiasRoute: NoticiasRoute,
  OndeComerRoute: OndeComerRoute,
  PerfilRoute: PerfilRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VagasRoute: VagasRoute,
  EmpresaIdRoute: EmpresaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
