/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OndeComerRouteImport } from './routes/onde-comer'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresaIdRouteImport } from './routes/empresa.$id'
import { Route as AuthenticatedPortalImprensaRouteImport } from './routes/_authenticated/portal-imprensa'
import { Route as AuthenticatedPainelImoveisRouteImport } from './routes/_authenticated/painel-imoveis'
import { Route as AuthenticatedPainelEmpresaRouteImport } from './routes/_authenticated/painel-empresa'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated/minha-conta'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminVagasRouteImport } from './routes/_authenticated/admin.vagas'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin.relatorios'
import { Route as AuthenticatedAdminParceirosRouteImport } from './routes/_authenticated/admin.parceiros'
import { Route as AuthenticatedAdminNoticiasRouteImport } from './routes/_authenticated/admin.noticias'
import { Route as AuthenticatedAdminInfluenciadoresRouteImport } from './routes/_authenticated/admin.influenciadores'
import { Route as AuthenticatedAdminImoveisRouteImport } from './routes/_authenticated/admin.imoveis'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin.eventos'
import { Route as AuthenticatedAdminEmpresasRouteImport } from './routes/_authenticated/admin.empresas'
import { Route as AuthenticatedAdminCuriosidadesRouteImport } from './routes/_authenticated/admin.curiosidades'
import { Route as AuthenticatedAdminCorretoresRouteImport } from './routes/_authenticated/admin.corretores'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminAprovacoesRouteImport } from './routes/_authenticated/admin.aprovacoes'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeComerRoute = OndeComerRouteImport.update({
  id: '/onde-comer',
  path: '/onde-comer',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaIdRoute = EmpresaIdRouteImport.update({
  id: '/empresa/$id',
  path: '/empresa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalImprensaRoute =
  AuthenticatedPortalImprensaRouteImport.update({
    id: '/portal-imprensa',
    path: '/portal-imprensa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelImoveisRoute =
  AuthenticatedPainelImoveisRouteImport.update({
    id: '/painel-imoveis',
    path: '/painel-imoveis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelEmpresaRoute =
  AuthenticatedPainelEmpresaRouteImport.update({
    id: '/painel-empresa',
    path: '/painel-empresa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVagasRoute = AuthenticatedAdminVagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParceirosRoute =
  AuthenticatedAdminParceirosRouteImport.update({
    id: '/parceiros',
    path: '/parceiros',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNoticiasRoute =
  AuthenticatedAdminNoticiasRouteImport.update({
    id: '/noticias',
    path: '/noticias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInfluenciadoresRoute =
  AuthenticatedAdminInfluenciadoresRouteImport.update({
    id: '/influenciadores',
    path: '/influenciadores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImoveisRoute =
  AuthenticatedAdminImoveisRouteImport.update({
    id: '/imoveis',
    path: '/imoveis',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmpresasRoute =
  AuthenticatedAdminEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCuriosidadesRoute =
  AuthenticatedAdminCuriosidadesRouteImport.update({
    id: '/curiosidades',
    path: '/curiosidades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCorretoresRoute =
  AuthenticatedAdminCorretoresRouteImport.update({
    id: '/corretores',
    path: '/corretores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAprovacoesRoute =
  AuthenticatedAdminAprovacoesRouteImport.update({
    id: '/aprovacoes',
    path: '/aprovacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guia': typeof GuiaRoute
  '/imoveis': typeof ImoveisRoute
  '/noticias': typeof NoticiasRoute
  '/onde-comer': typeof OndeComerRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vagas': typeof VagasRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/painel-empresa': typeof AuthenticatedPainelEmpresaRoute
  '/painel-imoveis': typeof AuthenticatedPainelImoveisRoute
  '/portal-imprensa': typeof AuthenticatedPortalImprensaRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/corretores': typeof AuthenticatedAdminCorretoresRoute
  '/admin/curiosidades': typeof AuthenticatedAdminCuriosidadesRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/imoveis': typeof AuthenticatedAdminImoveisRoute
  '/admin/influenciadores': typeof AuthenticatedAdminInfluenciadoresRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/parceiros': typeof AuthenticatedAdminParceirosRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vagas': typeof AuthenticatedAdminVagasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guia': typeof GuiaRoute
  '/imoveis': typeof ImoveisRoute
  '/noticias': typeof NoticiasRoute
  '/onde-comer': typeof OndeComerRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vagas': typeof VagasRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/painel-empresa': typeof AuthenticatedPainelEmpresaRoute
  '/painel-imoveis': typeof AuthenticatedPainelImoveisRoute
  '/portal-imprensa': typeof AuthenticatedPortalImprensaRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/corretores': typeof AuthenticatedAdminCorretoresRoute
  '/admin/curiosidades': typeof AuthenticatedAdminCuriosidadesRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/imoveis': typeof AuthenticatedAdminImoveisRoute
  '/admin/influenciadores': typeof AuthenticatedAdminInfluenciadoresRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/parceiros': typeof AuthenticatedAdminParceirosRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vagas': typeof AuthenticatedAdminVagasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/guia': typeof GuiaRoute
  '/imoveis': typeof ImoveisRoute
  '/noticias': typeof NoticiasRoute
  '/onde-comer': typeof OndeComerRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vagas': typeof VagasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/_authenticated/painel-empresa': typeof AuthenticatedPainelEmpresaRoute
  '/_authenticated/painel-imoveis': typeof AuthenticatedPainelImoveisRoute
  '/_authenticated/portal-imprensa': typeof AuthenticatedPortalImprensaRoute
  '/empresa/$id': typeof EmpresaIdRoute
  '/_authenticated/admin/aprovacoes': typeof AuthenticatedAdminAprovacoesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/corretores': typeof AuthenticatedAdminCorretoresRoute
  '/_authenticated/admin/curiosidades': typeof AuthenticatedAdminCuriosidadesRoute
  '/_authenticated/admin/empresas': typeof AuthenticatedAdminEmpresasRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/imoveis': typeof AuthenticatedAdminImoveisRoute
  '/_authenticated/admin/influenciadores': typeof AuthenticatedAdminInfluenciadoresRoute
  '/_authenticated/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/_authenticated/admin/parceiros': typeof AuthenticatedAdminParceirosRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/vagas': typeof AuthenticatedAdminVagasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/guia'
    | '/imoveis'
    | '/noticias'
    | '/onde-comer'
    | '/perfil'
    | '/sitemap.xml'
    | '/vagas'
    | '/admin'
    | '/minha-conta'
    | '/painel-empresa'
    | '/painel-imoveis'
    | '/portal-imprensa'
    | '/empresa/$id'
    | '/admin/aprovacoes'
    | '/admin/configuracoes'
    | '/admin/corretores'
    | '/admin/curiosidades'
    | '/admin/empresas'
    | '/admin/eventos'
    | '/admin/financeiro'
    | '/admin/imoveis'
    | '/admin/influenciadores'
    | '/admin/noticias'
    | '/admin/parceiros'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/admin/vagas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/guia'
    | '/imoveis'
    | '/noticias'
    | '/onde-comer'
    | '/perfil'
    | '/sitemap.xml'
    | '/vagas'
    | '/minha-conta'
    | '/painel-empresa'
    | '/painel-imoveis'
    | '/portal-imprensa'
    | '/empresa/$id'
    | '/admin/aprovacoes'
    | '/admin/configuracoes'
    | '/admin/corretores'
    | '/admin/curiosidades'
    | '/admin/empresas'
    | '/admin/eventos'
    | '/admin/financeiro'
    | '/admin/imoveis'
    | '/admin/influenciadores'
    | '/admin/noticias'
    | '/admin/parceiros'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/admin/vagas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/guia'
    | '/imoveis'
    | '/noticias'
    | '/onde-comer'
    | '/perfil'
    | '/sitemap.xml'
    | '/vagas'
    | '/_authenticated/admin'
    | '/_authenticated/minha-conta'
    | '/_authenticated/painel-empresa'
    | '/_authenticated/painel-imoveis'
    | '/_authenticated/portal-imprensa'
    | '/empresa/$id'
    | '/_authenticated/admin/aprovacoes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/corretores'
    | '/_authenticated/admin/curiosidades'
    | '/_authenticated/admin/empresas'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/imoveis'
    | '/_authenticated/admin/influenciadores'
    | '/_authenticated/admin/noticias'
    | '/_authenticated/admin/parceiros'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/vagas'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GuiaRoute: typeof GuiaRoute
  ImoveisRoute: typeof ImoveisRoute
  NoticiasRoute: typeof NoticiasRoute
  OndeComerRoute: typeof OndeComerRoute
  PerfilRoute: typeof PerfilRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VagasRoute: typeof VagasRoute
  EmpresaIdRoute: typeof EmpresaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-comer': {
      id: '/onde-comer'
      path: '/onde-comer'
      fullPath: '/onde-comer'
      preLoaderRoute: typeof OndeComerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/$id': {
      id: '/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/empresa/$id'
      preLoaderRoute: typeof EmpresaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal-imprensa': {
      id: '/_authenticated/portal-imprensa'
      path: '/portal-imprensa'
      fullPath: '/portal-imprensa'
      preLoaderRoute: typeof AuthenticatedPortalImprensaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-imoveis': {
      id: '/_authenticated/painel-imoveis'
      path: '/painel-imoveis'
      fullPath: '/painel-imoveis'
      preLoaderRoute: typeof AuthenticatedPainelImoveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-empresa': {
      id: '/_authenticated/painel-empresa'
      path: '/painel-empresa'
      fullPath: '/painel-empresa'
      preLoaderRoute: typeof AuthenticatedPainelEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vagas': {
      id: '/_authenticated/admin/vagas'
      path: '/vagas'
      fullPath: '/admin/vagas'
      preLoaderRoute: typeof AuthenticatedAdminVagasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parceiros': {
      id: '/_authenticated/admin/parceiros'
      path: '/parceiros'
      fullPath: '/admin/parceiros'
      preLoaderRoute: typeof AuthenticatedAdminParceirosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/noticias': {
      id: '/_authenticated/admin/noticias'
      path: '/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/influenciadores': {
      id: '/_authenticated/admin/influenciadores'
      path: '/influenciadores'
      fullPath: '/admin/influenciadores'
      preLoaderRoute: typeof AuthenticatedAdminInfluenciadoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/imoveis': {
      id: '/_authenticated/admin/imoveis'
      path: '/imoveis'
      fullPath: '/admin/imoveis'
      preLoaderRoute: typeof AuthenticatedAdminImoveisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/empresas': {
      id: '/_authenticated/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/curiosidades': {
      id: '/_authenticated/admin/curiosidades'
      path: '/curiosidades'
      fullPath: '/admin/curiosidades'
      preLoaderRoute: typeof AuthenticatedAdminCuriosidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/corretores': {
      id: '/_authenticated/admin/corretores'
      path: '/corretores'
      fullPath: '/admin/corretores'
      preLoaderRoute: typeof AuthenticatedAdminCorretoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aprovacoes': {
      id: '/_authenticated/admin/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/admin/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAdminAprovacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAprovacoesRoute: typeof AuthenticatedAdminAprovacoesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminCorretoresRoute: typeof AuthenticatedAdminCorretoresRoute
  AuthenticatedAdminCuriosidadesRoute: typeof AuthenticatedAdminCuriosidadesRoute
  AuthenticatedAdminEmpresasRoute: typeof AuthenticatedAdminEmpresasRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminImoveisRoute: typeof AuthenticatedAdminImoveisRoute
  AuthenticatedAdminInfluenciadoresRoute: typeof AuthenticatedAdminInfluenciadoresRoute
  AuthenticatedAdminNoticiasRoute: typeof AuthenticatedAdminNoticiasRoute
  AuthenticatedAdminParceirosRoute: typeof AuthenticatedAdminParceirosRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVagasRoute: typeof AuthenticatedAdminVagasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAprovacoesRoute: AuthenticatedAdminAprovacoesRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminCorretoresRoute: AuthenticatedAdminCorretoresRoute,
  AuthenticatedAdminCuriosidadesRoute: AuthenticatedAdminCuriosidadesRoute,
  AuthenticatedAdminEmpresasRoute: AuthenticatedAdminEmpresasRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminImoveisRoute: AuthenticatedAdminImoveisRoute,
  AuthenticatedAdminInfluenciadoresRoute:
    AuthenticatedAdminInfluenciadoresRoute,
  AuthenticatedAdminNoticiasRoute: AuthenticatedAdminNoticiasRoute,
  AuthenticatedAdminParceirosRoute: AuthenticatedAdminParceirosRoute,
  AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminVagasRoute: AuthenticatedAdminVagasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedPainelEmpresaRoute: typeof AuthenticatedPainelEmpresaRoute
  AuthenticatedPainelImoveisRoute: typeof AuthenticatedPainelImoveisRoute
  AuthenticatedPortalImprensaRoute: typeof AuthenticatedPortalImprensaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedPainelEmpresaRoute: AuthenticatedPainelEmpresaRoute,
  AuthenticatedPainelImoveisRoute: AuthenticatedPainelImoveisRoute,
  AuthenticatedPortalImprensaRoute: AuthenticatedPortalImprensaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GuiaRoute: GuiaRoute,
  ImoveisRoute: ImoveisRoute,
  NoticiasRoute: NoticiasRoute,
  OndeComerRoute: OndeComerRoute,
  PerfilRoute: PerfilRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VagasRoute: VagasRoute,
  EmpresaIdRoute: EmpresaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
