/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OndeComerRouteImport } from './routes/onde-comer'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresaIdRouteImport } from './routes/empresa.$id'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeComerRoute = OndeComerRouteImport.update({
  id: '/onde-comer',
  path: '/onde-comer',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaIdRoute = EmpresaIdRouteImport.update({
  id: '/empresa/$id',
  path: '/empresa/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guia': typeof GuiaRoute
  '/imoveis': typeof ImoveisRoute
  '/noticias': typeof NoticiasRoute
  '/onde-comer': typeof OndeComerRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vagas': typeof VagasRoute
  '/empresa/$id': typeof EmpresaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guia': typeof GuiaRoute
  '/imoveis': typeof ImoveisRoute
  '/noticias': typeof NoticiasRoute
  '/onde-comer': typeof OndeComerRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vagas': typeof VagasRoute
  '/empresa/$id': typeof EmpresaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guia': typeof GuiaRoute
  '/imoveis': typeof ImoveisRoute
  '/noticias': typeof NoticiasRoute
  '/onde-comer': typeof OndeComerRoute
  '/perfil': typeof PerfilRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vagas': typeof VagasRoute
  '/empresa/$id': typeof EmpresaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guia'
    | '/imoveis'
    | '/noticias'
    | '/onde-comer'
    | '/perfil'
    | '/sitemap.xml'
    | '/vagas'
    | '/empresa/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guia'
    | '/imoveis'
    | '/noticias'
    | '/onde-comer'
    | '/perfil'
    | '/sitemap.xml'
    | '/vagas'
    | '/empresa/$id'
  id:
    | '__root__'
    | '/'
    | '/guia'
    | '/imoveis'
    | '/noticias'
    | '/onde-comer'
    | '/perfil'
    | '/sitemap.xml'
    | '/vagas'
    | '/empresa/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuiaRoute: typeof GuiaRoute
  ImoveisRoute: typeof ImoveisRoute
  NoticiasRoute: typeof NoticiasRoute
  OndeComerRoute: typeof OndeComerRoute
  PerfilRoute: typeof PerfilRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VagasRoute: typeof VagasRoute
  EmpresaIdRoute: typeof EmpresaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-comer': {
      id: '/onde-comer'
      path: '/onde-comer'
      fullPath: '/onde-comer'
      preLoaderRoute: typeof OndeComerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/$id': {
      id: '/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/empresa/$id'
      preLoaderRoute: typeof EmpresaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuiaRoute: GuiaRoute,
  ImoveisRoute: ImoveisRoute,
  NoticiasRoute: NoticiasRoute,
  OndeComerRoute: OndeComerRoute,
  PerfilRoute: PerfilRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VagasRoute: VagasRoute,
  EmpresaIdRoute: EmpresaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
